// <auto-generated />
namespace PharmaCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Create_FirstTime_DataBase_and_AdminModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_FirstTime_DataBase_and_AdminModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202412171133012_Create_FirstTime_DataBase_and_AdminModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
